version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rails
    versions:
    - 6.1.1
    - 6.1.2
  - dependency-name: listen
    versions:
    - 3.4.0
