development:
  adapter: sqlite3
  encoding: unicode
  database: databasename
  pool: 5
  username: admin
  password: admin
test:
  adapter: sqlite3
  encoding: unicode
  database: testdatabasename
  pool: 5
  username: admin
  password: admin

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  database: ror_blog_production
  username: ror_blog
  password: <%= ENV['ROR_BLOG_DATABASE_PASSWORD'] %>
  timeout: 5000