development:
  adapter: sqlite3
  encoding: unicode
  database: databasename
  pool: 5
  username: admin
  password: admin
test:
  adapter: sqlite3
  encoding: unicode
  database: testdatabasename
  pool: 5
  username: admin
  password: admin

production:
  adapter: postgresql
  encoding: unicode
  database: productiondatabasename
  pool: 5
  username: admin
  password: admin